
[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]
  included_files = ["src/**/*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  functions = "functions"
  publish = "public"