[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "16"